# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target 'Geoguess' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Geoguess
  pod 'GoogleMaps', '7.4.0'

  target 'GeoguessTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeoguessUITests' do
    # Pods for testing
  end

end
